// <auto-generated />
using System;
using LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LuisaKatrinaReyes.Ecommerse.Web.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Category", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TagLine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Product", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TagLine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.ProductTag", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Tag", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8dbc96e-0017-4040-870a-bba392a940a0"),
                            CreatedAt = new DateTime(2021, 5, 14, 4, 25, 12, 179, DateTimeKind.Utc).AddTicks(3092),
                            Name = "Tag 1",
                            UpdatedAt = new DateTime(2021, 5, 14, 4, 25, 12, 179, DateTimeKind.Utc).AddTicks(4094)
                        },
                        new
                        {
                            Id = new Guid("32febb22-f596-4b1e-b0a8-b11ad54be201"),
                            CreatedAt = new DateTime(2021, 5, 14, 4, 25, 12, 179, DateTimeKind.Utc).AddTicks(7308),
                            Name = "Tag 2",
                            UpdatedAt = new DateTime(2021, 5, 14, 4, 25, 12, 179, DateTimeKind.Utc).AddTicks(7346)
                        },
                        new
                        {
                            Id = new Guid("32febb22-f596-4b1e-b0a8-b11ad54be202"),
                            CreatedAt = new DateTime(2021, 5, 14, 4, 25, 12, 179, DateTimeKind.Utc).AddTicks(7415),
                            Name = "Tag 3",
                            UpdatedAt = new DateTime(2021, 5, 14, 4, 25, 12, 179, DateTimeKind.Utc).AddTicks(7431)
                        });
                });

            modelBuilder.Entity("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Product", b =>
                {
                    b.HasOne("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.ProductTag", b =>
                {
                    b.HasOne("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("LuisaKatrinaReyes.Ecommerse.Web.Infrastructure.Domain.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");
                });
#pragma warning restore 612, 618
        }
    }
}
